[tools]
# Needed for mise shell completion.
usage = "latest"

# Language support.
java = "temurin"
node = "latest"
poetry = "latest"
python = "latest"
ruby = "latest"

[settings]
experimental = true

