#!/bin/zsh

function drawblock {
    printf '\005{%s}[\005{%s} ' "${BLOCK_COLOR}" "${TEXT_COLOR}"

    format="$1"
    shift
    printf "${format}" $@

    printf '\005{%s} ]\005{%s}' "${BLOCK_COLOR}" "${TEXT_COLOR}"
}

