#!/bin/zsh

function drawbar {
    local steps="$1"
    local percent="$2"
    shift 2

    local n_hashes=$(( (percent + 5) * steps / 100 ))

    for opt in $@
    do
        local level=''
        local color=''
        echo "${opt}" | sed 's/:/ /' | read level color

        if ((percent <= level))
        then
            break
        fi
    done

    printf '\005{%s}' "${color}"

    local i
    for ((i=0; i < n_hashes; ++i))
    do
        printf '#'
    done

    printf '\005{%s}' "${BAR_BG_COLOR}"

    for ((i=n_hashes; i < steps; ++i))
    do
        printf '='
    done
}

