#!/usr/bin/env zsh

case $(uname) in
    Darwin)
        alias gvim='mvim'
        alias ls='ls -hFG'
        ;;
    *)
        alias ls='ls -hF --color=auto'
        ;;
esac

alias df='df -hT'
alias du='du -hk'

alias grep='grep --color=auto'

alias ll='ls -l'
alias la='ls -A'
alias lal='ls -lA'
alias ldl='ls -ld'

alias ssh333='TERM=xterm ssh -t csi333 screen -s /usr/bin/zsh'

alias wwwdo='sudo -u www'

alias playlist="mpc playlist -f '[%position% ][[%albumartist%|%artist% - ]%title%]|[%file%]'"

function cthulhu {
    echo "ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn" >&2
}

function google {
    elinks "http://www.google.com/search?q=${*// /+}"
}

function ignore {
    $@ &>/dev/null &!
}

