#!/usr/bin/env zsh

source $HOME/.zsh/liquidprompt/liquidprompt

function preexec {
    local cmd=${1[(wr)^(*=*|sudo|exec|builtin|command|nocorrect|noglob|-*)]}
    local job

    if [[ $cmd == 'fg' && -n $jobstates ]]
    then
        job=$(jobs %+ | cut -d ' ' -f5-)
        preexec $job
        return $?
    fi

    printf '\033]0;%s %s\007' ${(%%)LP_TITLE_PS1} $cmd
}

