#!/usr/bin/env zsh

source $HOME/.zsh/liquidprompt/liquidprompt

function preexec {
    local HOSTNAME="$(hostname)"
    local CMD=${2[(wr)^(*=*|sudo|exec|command|nocorrect|noglob|-*)]}

    if [ "$CMD" = 'fg' ] && [ -n "$jobstates" ]
    then
        CMD=$(jobs %+ | awk '{print $4}')
    fi

    if [ -z "$SSH_CONNECTION" ]
    then
        printf '\033]0;%s\007' $CMD
    else
        printf '\033]0;%s:%s\007' $CMD $HOSTNAME
    fi
}

