#!/usr/bin/env zsh

bindkey -v

# if [[ $(uname) != Darwin ]]
# then
#     setterm -blank 0
# fi

stty start ""
stty stop ""

if (($+terminfo[kbs]))
then
    bindkey -M viins $terminfo[kbs] backward-delete-char
else
    bindkey -M viins '^?' backward-delete-char
    bindkey -M viins '^H' backward-delete-char
fi

if (($+terminfo[kdch1]))
then
    bindkey -M viins $terminfo[kdch1] delete-char
fi

bindkey -M viins 'jj' vi-cmd-mode
bindkey -M viins 'kk' vi-cmd-mode

bindkey -M vicmd -s ';' ':'
bindkey -M vicmd ',zf' fzf-file-widget
bindkey -M vicmd ',zh' fzf-history-widget

