#!/usr/bin/env zsh

function fzf-file-widget {
    LBUFFER+=$(find * -path '*/\\.*' -prune \
        -o -type f -print \
        -o -type l -print 2>/dev/null \
        | fzf)
    zle redisplay
}

function fzf-history-widget {
    LBUFFER+=$(history | fzf +s | sed 's/ *[0-9]* *//')
    zle redisplay
}

zle -N fzf-file-widget
zle -N fzf-history-widget

bindkey '^T' fzf-file-widget
bindkey '^Y' fzf-history-widget

