#!/usr/bin/env zsh

case $(uname) in
    Darwin)
        source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        ;;
    *)
        source /usr/share/chris/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        ;;
esac

