#!/usr/bin/env zsh

if which screen &>/dev/null
then
    START_SCREEN=1
else
    START_SCREEN=0
fi

if [[ "$TERM" = *screen* ]] || [[ $- != *i* ]] || [[ $- != *l* ]] || [[ -e "$HOME/.noscreen" ]]
then
    START_SCREEN=0
fi

